#-------------------------------
# General Site Settings

title: Iyer's Filter Coffee
description: Garage Rock // Indie // Bangalore 
email: iyersfiltercoffee@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About The Band, url: '#about-me'}
- {name: Videos, url: '#work'}
- {name: Band Profile, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Iyer's Filter Coffee** band description.band description.band description.band description.band description.band description.band description.band description.band description.band description.band description.band description.band description.

#skills:
#- {name: Communication, value: '9'}
#- {name: Organization, value: '7'}
#- {name: Learning, value: '10'}
#- {name: Teaching, value: '6'}
#- {name: Planning, value: '7'}
#- {name: Visual Design, value: '5'}
#- {name: UX Design, value: '8'}
#- {name: Programming, value: '6'}

#-------------------------------
# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: City-IN website concept, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-aaroni.jpg',
  name: 'Dennis Dey',
  title: 'Bassist',
  quote: '<p>Dennis DeyDennis DeyDennis DeyDennis DeyDennis DeyDennis DeyDennis DeyDennis DeyDennis DeyDennis DeyDennis DeyDennis DeyDennis DeyDennis Dey..............</p>',
  logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Rushil Mishra',
  title: 'Vocalist',
  quote: '<p>Rushil MishraRushil MishraRushil MishraRushil MishraRushil MishraRushil MishraRushil MishraRushil MishraRushil MishraRushil MishraRushil Mishra...........</p>',
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Pushkara Ravindra',
  title: 'Guitarist',
  quote: '<p>Pushkar RavindraPushkar RavindraPushkar RavindraPushkar RavindraPushkar RavindraPushkar RavindraPushkar RavindraPushkar RavindraPushkar Ravindra.........</p>',
  logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Sachin Iyer',
  title: 'VP of Helmut, Lorem Sorem LLC.',
  quote: '<p>Sachin IyerSachin IyerSachin IyerSachin IyerSachin IyerSachin IyerSachin IyerSachin IyerSachin IyerSachin IyerSachin IyerSachin IyerSachin Iyer.............</p>',
  logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
